openapi: 3.0.0
info:
  title: Sample API
  description: A simple API to demonstrate OpenAPI versioning.
  version: 1.0.0
paths:
  /login:
    post:
      summary: User login
      description: Endpoint for user login.
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid login credentials
      content:
        text/html:
          schema:
            type: string
            example: |
              <div class="message">
                <h1>Welcome to the Login Page</h1>
                <p>Please enter your credentials to continue.</p>
              </div>
